name: flight-tracker

networks:
  redpanda_network:

volumes:
  redpanda-0:

services:
  redpanda-0:
    image: docker.redpanda.com/redpandadata/redpanda:v26.1.9
    container_name: redpanda-0
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    volumes:
      - redpanda-0:/var/lib/redpanda/data
    networks:
      - redpanda_network
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info", "--brokers", "redpanda-0:9092"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  init-redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v26.1.9
    container_name: init-redpanda
    entrypoint: /bin/sh
    command:
      - -c
      - rpk topic create adsb.raw   --if-not-exists --brokers redpanda-0:9092 && rpk topic create adsb.parsed --if-not-exists --brokers redpanda-0:9092 && rpk topic create adsb.state  --if-not-exists --brokers redpanda-0:9092 --config cleanup.policy=compact
    networks:
      - redpanda_network
    depends_on:
      redpanda-0:
        condition: service_healthy

  console:
    image: docker.redpanda.com/redpandadata/console:v3.7.4
    container_name: redpanda-console
    networks:
      - redpanda_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-0:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://redpanda-0:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-0:9644"]
    ports:
      - "8080:8080"
    depends_on:
      init-redpanda:
        condition: service_completed_successfully

  api:
    build: ./api
    container_name: api
    networks:
      - redpanda_network
    ports:
      - "3000:3000"
    environment:
      KAFKA_BROKERS: "redpanda-0:9092"
    depends_on:
      redpanda-0:
        condition: service_healthy

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.5.14
    container_name: ksqldb-server
    networks:
      - redpanda_network
    volumes:
      - ./ksqldb/processor:/processor:ro
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_BOOTSTRAP_SERVERS: "redpanda-0:9092"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://redpanda-0:8081"
      KSQL_KSQL_QUERIES_FILE: "/processor/queries.sql"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
    depends_on:
      redpanda-0:
        condition: service_healthy
